apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mldm-staging
namePrefix: stg-

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/instance: mldm-agent-staging
  env: staging

images:
  - name: mldm-agent
    newName: us-central1-docker.pkg.dev/PROJECT_ID/mldm/mldm-agent
    newTag: staging

replicas:
  - name: mldm-agent
    count: 2

patches:
  - path: configmap-staging.yaml
    target:
      kind: ConfigMap
      name: mldm-agent-config
